.TH SECRET
.SH NAME
secret \- send or receive file using secret ICMP protocol
.SH SYNOPSIS
\fB\-r\fR FILENAME
\fB\-s\fR IP/HOSTNAME
[\fB\-l\fR]
.SH DESCRIPTION
.B secret
Sends or receives file using secret ICMP protocol.
.SH OPTIONS
.TP
.BR \-r " "FILENAME
Specifies file to send.
.TP
.BR \-s " "IP/HOSTNAME
Specifies IP address or hostname which the file will be send to.
.TP
.BR \-l " "optional
Program runs as a server